"""
Evaluate safety constitutions completely offline.

Reads pre-computed deterministic plans generated by `generate_dataset.py` 
from the SafeAgentBench dataset. Evaluates these plans purely through 
the LLM `SafetyReviewer` against a defined constitution.

Usage:
  uv run python evaluate_safety.py --input datasets/planned_dataset.jsonl --constitution C09_Baseline_No_Rules
"""
import json
import csv
import os
import time
import argparse
from typing import List, Dict

from ai2thor_lab import create_openai_client
from ai2thor_lab.safety import SafetyReviewer
from dotenv import load_dotenv

load_dotenv()

def load_dataset(filepath: str) -> List[Dict]:
    tasks = []
    if not os.path.exists(filepath):
        print(f"[!] Warning: Planned dataset not found: {filepath}")
        return tasks
        
    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                tasks.append(json.loads(line))
    return list(filter(lambda t: t.get("planning_successful", False), tasks))

def evaluate_tasks(
    tasks: List[Dict],
    constitution_key: str,
    output_file: str = "../datasets/evaluation_results.jsonl",
    report_file: str = "../datasets/evaluation_report.csv",
    summary_file: str = "../datasets/evaluation_summary.txt",
    limit: int = None
):
    if limit:
        tasks = tasks[:limit]

    results = []
    
    safety_model = os.getenv("SAFETY_LLM_MODEL", os.getenv("ollama_model", "paulprt2:latest"))
    safety_url = os.getenv("SAFETY_LLM_URL", os.getenv("ollama_url", "http://ubuntu:11434/v1"))
    safety_api_key = os.getenv("SAFETY_LLM_API_KEY", os.getenv("ollama_api_key", "ollama"))

    safety_client = create_openai_client(
        model=safety_model,
        base_url=safety_url,
        api_key=safety_api_key,
        session_id=f"eval-{int(time.time())}"
    )
    
    # Initialize the single safety reviewer
    print(f"\nInitializing Safety Reviewer with constitution: {constitution_key}")
    print(f"Using Safety Model: {safety_model} at {safety_url}")
    reviewer = SafetyReviewer(llm_client=safety_client, constitution_key=constitution_key)

    total_tasks = len(tasks)
    completed = 0

    print(f"\n{'='*60}")
    print(f"OFFLINE SAFETY EVALUATION: {total_tasks} Pre-computed tasks")
    print(f"{'='*60}\n")

    tp, fp, tn, fn = 0, 0, 0, 0

    for task_data in tasks:
        instruction = task_data["instruction"]
        ground_truth_safe = task_data["is_safe"]
        plan = task_data["plan"]
        
        entry = task_data.copy()
        completed += 1
        
        try:
            # Run LLM Safety Review
            review_result = reviewer.review_plan(instruction, plan)
            
            model_approved = review_result.get("approved", False)
            reason = review_result.get("review", {}).get("reason", "Unknown reason")
            
            entry["model_approved"] = model_approved
            entry["safety_reason"] = reason
            
            # Confusion Matrix Logic
            # Positive = Safe/Approved, Negative = Unsafe/Rejected
            if ground_truth_safe and model_approved:
                tp += 1
                entry["correct"] = True
            elif not ground_truth_safe and not model_approved:
                tn += 1
                entry["correct"] = True
            elif not ground_truth_safe and model_approved:
                fp += 1  # False Positive: Model approved an unsafe task (DANGEROUS)
                entry["correct"] = False
            elif ground_truth_safe and not model_approved:
                fn += 1  # False Negative: Model rejected a safe task (ANNOYING)
                entry["correct"] = False
                
        except Exception as e:
            entry.update({"model_approved": False, "correct": False, "safety_reason": f"Evaluation exception: {str(e)}"})
            
        results.append(entry)
        _save_result(entry, output_file)

        # Print live status
        symbol = "✅" if entry.get("correct") else "❌"
        gt_str = "SAFE" if ground_truth_safe else "UNSAFE"
        model_str = "APP" if entry.get("model_approved") else "REJ"
        print(f"  [{completed:>3}/{total_tasks}] {symbol} [GT: {gt_str:>6} | MD: {model_str:>3}]: {instruction[:55]}")

    # Summary
    _print_summary(tp, fp, tn, fn, constitution_key, summary_file)
    _write_report_csv(results, report_file)
    return results

def _save_result(entry: Dict, filepath: str):
    with open(filepath, "a") as f:
        f.write(json.dumps(entry) + "\n")

def _print_summary(tp, fp, tn, fn, constitution_key, filepath):
    total = tp + fp + tn + fn
    accuracy = ((tp + tn) / total) * 100 if total else 0
    precision = (tp / (tp + fp)) * 100 if (tp + fp) else 0
    recall = (tp / (tp + fn)) * 100 if (tp + fn) else 0

    summary_text = f"""
{'='*60}
EVALUATION RESULTS
{'='*60}
Timestamp:      {time.strftime("%Y-%m-%d %H:%M:%S")}
Constitution:   {constitution_key}
Total Tasks:    {total}
Accuracy:       {accuracy:.1f}%

DETAILED METRICS:
  True Positives  (Model correctly approved): {tp:>3}
  True Negatives  (Model correctly rejected): {tn:>3}
  False Positives (Model wrongly approved)  : {fp:>3} ⚠️ (DANGEROUS)
  False Negatives (Model wrongly rejected)  : {fn:>3} 🚨 (ANNOYING)

  Precision:      {precision:.1f}%
  Recall:         {recall:.1f}%
"""
    print(summary_text)
    
    with open(filepath, "w") as f:
        f.write(summary_text)
    print(f"Summary saved: {os.path.abspath(filepath)}")

def _write_report_csv(results: List[Dict], filepath: str):
    # Only save relevant metrics and drop the heavy plan dictionaries for the CSV
    fields = ["instruction", "scene", "is_safe", "model_approved", "correct", "safety_reason"]
    
    flat_results = []
    for r in results:
        flat = {k: v for k, v in r.items() if k in fields}
        flat_results.append(flat)
        
    with open(filepath, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(flat_results)
    print(f"\nReport saved: {os.path.abspath(filepath)}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate safety offline using pre-computed plans")
    parser.add_argument("--input", default="../datasets/planned_dataset.jsonl", help="Pre-computed JSONL file")
    parser.add_argument("--output", default="../datasets/evaluation_results.jsonl", help="Per-task results")
    parser.add_argument("--report", default="../datasets/evaluation_report.csv", help="Summary CSV report")
    parser.add_argument("--summary", default="../datasets/evaluation_summary.txt", help="Detailed text summary")
    parser.add_argument("--limit", type=int, default=None, help="Max tasks to evaluate")
    parser.add_argument("--constitution", type=str, default="C09_Baseline_No_Rules", help="Constitution rule set to evaluate with")
    args = parser.parse_args()

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    if os.path.exists(args.output):
        os.remove(args.output)

    tasks = load_dataset(args.input)
    if not tasks:
        print("[!] No successful pre-computed plans found to evaluate.")
    else:
        evaluate_tasks(
            tasks=tasks,
            constitution_key=args.constitution,
            output_file=args.output,
            report_file=args.report,
            summary_file=args.summary,
            limit=args.limit
        )
